### ISSUE TITLE
Can I help add Postman as a 'browser'?

### ISSUE THREAD

**Issue by acunniffe** [httptoolkit/browser-launcher#10]
I've been playing around with this library and am impressed by all the work that's gone into managing the lifecycle, profiles and configs for each of the spawned processes. 

I wonder if we can expand the definition of 'browser' to include Postman. I experimented last night with adding Postman + commands to open it, and can confirm that you can make it use a transparent proxy by setting 'HTTP_PROXY' and 'HTTPS_PROXY' in the shell you launch it from. Is this the sort of contribution that would be accepted to the proxy?

**Comment by pimterry** [comment]
Hmmmmm, I'm a bit resistant, since it's not really a browser, I'm not sure it's that relevant to this module  (although I can see how it's relevant to Optic!) and it doesn't seem like it would share much logic either. Maybe it should be a standalone module?

Or if it's just launching the process with environment variables, that sounds very simple, why does it need to be a module at all? Or are there other details you're looking for?

If you're looking to intercept Electron apps automatically, HTTP Toolkit server can do that in the general case, for Postman and others: https://github.com/httptoolkit/httptoolkit-server/blob/master/src/interceptors/electron.ts. Doing so is a little more complicated than just the env vars. Env vars generally aren't used by node.js HTTP clients inside Electron's main process, which tend to ignore these settings. They'll only affect requests from the renderer, or from apps that specifically handle them (might include Postman, I'm not sure). Capturing that extra traffic too is possible by automatically attaching a debugger at startup and injecting some reconfiguration code before the main app runs.

**Comment by acunniffe** [comment]
This makes sense! Thanks @pimterry — I played around a bit more with Postman and think I know how I’ll do it.

In general I don’t think I need it to be in the middle, but was hoping to maybe give back :) 

thanks for all you do!
